### PR TITLE
fix: remaining fixes from previous PRs

### LINKED ISSUE #257: Follow-up fixes
From PRs #254 and #255, some comments were left unresolved to be fixed in a follow-up PR:

- Rename of `QuaiPayInputDisplay` -> `QuaiPayAmountDisplay`
- SendTip screen if statement simplification
- ~Putting `DismissKeyboard` inside `QuaiPayContent`~ EDIT: no need for this one since there are no keyboards worth removing

### PR DESCRIPTION
**Pull request by juanmanso**
## Related links

- #254 
- #255 
- Closes #257 

## Proof

| _Demo_ |
| :---: |
| <video src='https://github.com/dominant-strategies/quaipay/assets/21087992/5f0d8baf-eac7-46cf-8b4c-aa56ee55bc26' width=400> |

### CODE REVIEW

File: src/main/home/send/SendTip.tsx [hunk 1]
```diff
@@ -97,36 +97,21 @@ const SendTipScreen = ({ route, navigation }: SendTipScreenProps) => {
   };
 
   const navigateToOverview = () => {
-    let tipInUSD: number;
     if (quaiRate) {
-      if (input.unit === Currency.USD) {
```
Comment (obasilakis) [inline src/main/home/send/SendTip.tsx:102]: you actually do need this check here. check it out:

https://github.com/dominant-strategies/quaipay/assets/33531476/5d3044f5-20d1-4047-8c90-c5d4945310ed

Comment (juanmanso) [reply src/main/home/send/SendTip.tsx:102]: Fixes pushed, sharing a demo below of how it works now:

| _Demo_ |
| :---: |
| <video src='https://github.com/dominant-strategies/quaipay/assets/21087992/5f0d8baf-eac7-46cf-8b4c-aa56ee55bc26' width=400> |

**Review by obasilakis — APPROVED** [review]
