### PR TITLE
fix: setup of pfp with blockie on context

### LINKED ISSUE #241: [Bug] Correctly store info for blockie pfps
The following error is produced because of storing the whole blockie pfp string in a QR Code.

| Image |
| :---: |

To fix this, we will store the zone instead of the uri for the pfp for blockies. Then, we will check if the stored string fits the regex for zone strings and generate the blockie if so.

### PR DESCRIPTION
**Pull request by juanmanso**
## Description

While implementing blockie pfps, we decided to store that uri string in the context and use that everywhere.

However, we found that the string might be a little too long and thus resulting in an issue while generating the QR code to share it.

Since this is a partial fix (the actual and complete fix would be to share the whole set of addresses for a contact), we defaulted on the send flow to use the address blockie if pfp is a zone.

That last part will be followed up in upcoming PRs.

## Related links

- Closes #241 

## Proof

| _Before_ | _After_ |
| :---: | :---: |
|  | image |

### CODE REVIEW

File: src/main/home/receive/ReceiveScreen.tsx [hunk 1]
```diff
@@ -34,7 +35,8 @@ export const ReceiveScreen = () => {
   const { showSnackBar } = useSnackBar();
   const isDarkMode = useColorScheme() === 'dark';
   const navigation = useNavigation<RootStackNavigationProps<'Main'>>();
-  const profilePicture = useProfilePicture();
+  const { profilePicture } = useWalletContext(); // get bare profile picture state
+  useProfilePicture(); // fetch profilePicture
```
Comment (obasilakis) [inline src/main/home/receive/ReceiveScreen.tsx:39]: this feels kinda strange. can't we use the PFP returned by `useProfilePicture`?

File: src/shared/hooks/useProfilePicture.ts [hunk 2]
```diff
@@ -8,5 +11,11 @@ export const useProfilePicture = (): string | undefined => {
...
   }, [profilePicture]);
-  return profilePicture;
+  return profilePicture && checkProfilePictureStringIsZone(profilePicture)
+    ? makeBlockie(profilePicture)
+    : profilePicture;
 };
+
+// Check by indexing Zone enum. If valid, it will be true
+const checkProfilePictureStringIsZone = (s: string) =>
+  !!Zone?.[s as keyof typeof Zone];
```
Comment (obasilakis) [inline src/shared/hooks/useProfilePicture.ts:21]: noice

**Review by obasilakis — APPROVED** [review]

File: src/main/home/receive/ReceiveScreen.tsx (hunk 1 above)
Comment (juanmanso) [reply src/main/home/receive/ReceiveScreen.tsx:39]: The thing is that we should have like another function that converts stored `profilePicture` on context to the actual image (and if it's a zone turn it into a blockie).

Do you think that I should get the raw `profilePicture` value from `useProfilePicture` and then handle it everytime we need the actual image? I think there are less times you gonna use the actual value than you are gonna need the image, but let me know what's your idea 😄

Comment (juanmanso) [reply src/main/home/receive/ReceiveScreen.tsx:39]: Creating a ticket for this to be handled gracefully when new contact structure is defined but resolving it for the time being
- #246
